name: BackEndAssign_240619
dependencies:
    - python=3.12.4 
    - pip=24.0  
    - pip:
      - django==5.0.6
      - djangorestframework==3.15.2
      - djangorestframework-simplejwt==5.3.1
      - drf-yasg==1.21.7
