# Generated by Django 5.0.6 on 2024-06-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_creator'),
        ('userProfile', '0002_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='postsLiked', to='userProfile.userprofile'),
        ),
    ]
