# Generated by Django 5.0.6 on 2024-06-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_likedby'),
        ('userProfile', '0002_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sharedBy',
            field=models.ManyToManyField(blank=True, related_name='postsShared', to='userProfile.userprofile'),
        ),
    ]
