# Generated by Django 5.0.6 on 2024-06-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0002_alter_userprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default="temporary_username", max_length=100),
        ),
    ]
