# Generated by Django 5.0.6 on 2024-06-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0003_userprofile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
