# Generated by Django 5.0.6 on 2024-06-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0002_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtCreated', models.DateTimeField(auto_now_add=True)),
                ('dtUpdated', models.DateTimeField(auto_now=True)),
                ('isFollowedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='userProfile.userprofile')),
                ('isFollowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='userProfile.userprofile')),
            ],
        ),
    ]
