# Generated by Django 5.0.6 on 2024-06-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='isFollowedBy',
            new_name='isFollowed',
        ),
    ]
