# Generated by Django 5.0.6 on 2024-06-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlMedia', models.CharField(max_length=255)),
                ('dtCreated', models.DateTimeField(auto_now_add=True)),
                ('dtUpdated', models.DateTimeField(auto_now=True)),
                ('postCommented', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='post.post')),
            ],
        ),
    ]
