# Generated by Django 5.0.6 on 2024-06-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='postCommented',
            new_name='postRelated',
        ),
    ]
