# Generated by Django 5.0.6 on 2024-06-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0002_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('dtCreated', models.DateTimeField(auto_now_add=True)),
                ('dtUpdated', models.DateTimeField(auto_now=True)),
                ('receivedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='userProfile.userprofile')),
                ('sendRequestTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='userProfile.userprofile')),
            ],
        ),
    ]
